// Обмеження для унікальності ID концепцій
CREATE CONSTRAINT IF NOT EXISTS ON (c:Concept) ASSERT c.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS ON (m:Material) ASSERT m.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS ON (t:Task) ASSERT t.id IS UNIQUE;